function getQuestions() {
  return [
    {
      question: "Press any button to start the quiz.",
      answers: [
        "1",
        "2",
        "Any button",
        "4",
        "5",
        "6",
        "7",
        "any button",
        "9",
        "10",
      ],
      answer: 8,
    },
    {
      question: "What is the capital of France?",
      answers: [
        "London",
        "paris",
        "Berlin",
        "Tokyo",
        "Nota L33T",
      ],
      answer: 5,
    },
    {
      question: "What is 5 + 7?",
      answer: "57",
    },
    {
      question: "What is the third month of the year?",
      answers: [
        "Marsh",
        "April",
        "Austin",
        "May",
        "June",
        "July",
      ],
      answer: 3,
    },
    {
      question: "Which planet is closest to the Sun?",
      answers: [
        "Saturn",
        "Neptune",
        "Mercury",
        "Venus",
        "The Sun has no friends.",
      ],
      answer: 5,
    },
    {
      question: "Where are the pyramids?",
      answers: [
        "India",
        "Egypt",
        "Morocco",
        "The dark alley round back",
        "Canada",
      ],
      answer: 5,
    },
    {
      question: "What is a quarter of 200?",
      answer: "25",
    },
    {
      question: "Which is the largest state in the USA?",
      answers: [
        "California",
        "There are no states.",
        "Alaska",
        "Florida",
        "Mexico",
        "Wyoming",
      ],
      answer: 6,
    },
    {
      question: "What is 7*19?",
      answer: "719",
    },
    {
      question: "What is L?",
      answers: [
        "Left",
        "R",
        "Pipe",
        "Right Angle",
      ],
      answer: 4,
    },
    {
      question: "Gik Chonilz",
      answers: [
        "MouseDucks",
        "Smash burgers",
        "Donald Duck",
        "Mickey Mouse",
      ],
      answer: 1,
    },
    {
      question: "Jres?",
      answers: [
        "$1,280,720.24",
        "$25 601 440.24",
        "$19,201,080.24",
        "$800,600.24",
      ],
      answer: 2,
    },
    {
      question: "?????+Cat",
      answers: [
        "Dog",
        "Jack",
        "Peg",
        "Pig",
      ],
      answer: 3,
    },
    {
      question: "WHat is 10k?",
      answers: [
        "....100000 Tentens",
        "1000000 Hundredths",
        "..10000000 Oneunos",
        ".100000000 Hundred",
      ],
      answer: 2,
    },
    {
      question: "What is 5 + 10?",
      answer: "15",
    },
    {
      question: "Count",
      answers: [
        "1",
        "2",
        "3",
        "4",
      ],
      answer: 1,
    },
    {
      question: "Count",
      answers: [
        "1",
        "2",
        "3",
        "4",
      ],
      answer: 2,
    },
    {
      question: "Count",
      answers: [
        "1",
        "2",
        "3",
        "4",
      ],
      answer: 3,
    },
    {
      question: "Count",
      answers: [
        "1",
        "2",
        "3",
        "4",
      ],
      answer: 4,
    },
    {
      question: "It's raining.",
      answers: [
        "Oh yeah?",
        "OR REALLY?",
        "Dooplol",
        "...man's best friends.",
      ],
      answer: 4,
    },
    {
      question: "Not creator's gender?",
      answers: [
        "Man",
        "Woah, man!",
        "Peanut Butter",
        "Girl",
      ],
      answer: 2,
    },
    {
      question: "I'm gonna guess it's not that funny.",
      answers: [
        "Me on mondays:",
        "My sister",
        "Like totally IKR",
        "UFO",
      ],
      answer: 3,
    },
    {
      question: "Lajedifolusapelibomudabekip!",
      answers: [
        "Pikebadumobilepasulofidejal!",
        "You on moodays:",
        "QWERTYUIOP",
        "POIUYTREWQ",
      ],
      answer: 1,
    },
    {
      question: "Hi0",
      answers: [
        "Hi1",
        "Hi2",
        "Hi3",
        "Hi4",
        "Hi5",
        "Hi6",
        "Hi7 <= Incorrect",
        "Hi8",
        "Hi9",
      ],
      answer: 7,
    },
    {
      question: "Die",
      answers: [
        "in",
        "a",
        "large",
        "hole",
        "!",
      ],
      answer: 3,
    },
    {
      question: "You",
      answers: [
        "don",
        "tde",
        "ser",
        "vet",
        "oex",
        "ist",
        "lol",
      ],
      answer: 7,
    },
    {
      question: "If doesn't anything Zelda don't.",
      answers: [
        "PB Teen",
        "Pottery",
        "Clay",
        "Peanut Butter Teen",
        "See, Weed?",
      ],
      answer: 4,
    },
    {
      question: "J.K. Rowling",
      answers: [
        "Just kidding, I'm rolling!",
        "K.J. Gnilwor",
        "I'm not kidding.",
      ],
      answer: 1,
    },
    {
      question: "Harry Potter",
      answers: [
        "A hairy potter",
        "A very hairy potty",
        "You're very hairy, Harry!",
        "You're a hairy wizard.",
        "Hairy Pasta",
      ],
      answer: 5,
    },
    {
      question: "Brayden",
      answers: [
        "Brenden",
        "Bring a den",
        "Lol",
        "Right angle kidz",
      ],
      answer: 4,
    },
    {
      question: "Count",
      answer: "5",
    },
    {
      question: "Sub-alien Sub Eaters?",
      answers: [
        "Quiznos",
        "Soubway",
        "Odd man",
        "7th whaal",
      ],
      answer: 4,
    },
    {
      question: "My sister likes the word large. Why?",
      answers: [
        "Because she is.",
        "Because her brain isn't.",
        "Because '.",
      ],
      answer: 3,
    },
    {
      question: "Ben is a midget because...",
      answers: [
        "...his parents were talk and they didn't have enough tall jeans left (DISCLAIMER: they aren't)",
        "...we encouraged him too much.",
        "...of the existance of an \"'\"'\"'\"'",
      ],
      answer: 2,
    },
    {
      question: "My sister  i  s      large.",
      answers: [
        "           ^",
        "          not",
        "Correct!",
      ],
      answer: 3,
    },
    {
      question: "Thou shalt eat carrots.",
      answers: [
        "Because thou shall.",
        "Because his brain isn't.",
        "Because of a \".",
        "Loloofapalooza!",
      ],
      answer: 3,
    },
    {
      question: "How many butts does an anaconda have?",
      answers: [
        "1",
        "8",
        "120",
        "5,612",
        "128,000",
        "5,000,000,002",
      ],
      answer: 6,
    },
    {
      question: "Don't count!",
      answers: [
        " ",
      ],
      answer: 1,
    },
    {
      question: "Frogger jumps on ???s.",
      answers: [
        "|≠≥",
        "(?)",
        "n√x",
        " √ ",
        "ln ",
        "log",
        "[] ",
        "{} ",
      ],
      answer: 6,
    },
    {
      question: "What is L?",
      answers: [
        "Left",
        "Right Angle Kidz",
        "Clock hands",
        "Left Angle",
      ],
      answer: 4,
    },
    {
      question: "Who are you?",
      answers: [
        "A Dragonez",
        "Trump McDonaldson",
        "Naydra",
        "Hydra",
      ],
      answer: 2,
    },
    {
      question: "Did the divyers make dat sound?",
      answers: [
        "Yes",
        "No",
        "Maybe",
        "So",
      ],
      answer: 4,
    },
    {
      question: "What is your title?",
      answers: [
        "Ms.",
        "Mrs.",
        "Mr.",
        "Dr.",
        "NOTA",
        "Woah, man!",
      ],
      answer: 6,
    },
    {
      question: "How do you spell PB Teen? (Penut Buter)",
      answer: "Peanut Butter",
    },
    {
      question: "How do you spell paniced?",
      answer: "panicked",
    },
    {
      question: "I'm thinking of a number between 1729402 and 2927494",
      answers: [
        "1. 19 ⨯ 6",
        "2. Add the digits",
        "3. ",
        "4. ",
        "5. ",
        "6. ",
        "7. ",
        "8. ",
      ],
      answer: 6,
    },
    {
      question: "Chu bef nugy!",
      answers: [
        "True",
        "False",
      ],
      answer: 1,
    },
    {
      question: "Bean",
      answers: [
        "Pasta",
      ],
      answer: 1,
    },
    {
      question: "schoooochlshooooshlashooooshaaaaaoooo",
      answers: [
        "Ben on moodays",
        "The sink",
        "...hole",
      ],
      answer: 3,
    },
    {
      question: " ",
      answers: [
        ";)",
        " ",
        " ",
        " ",
      ],
      answer: 1,
    },
    {
      question: "Which one is incorrect?",
      answers: [
        "SON's day",
        "MOON day",
        "TIEW's day",
        "WODEN's day",
        "THOR's day",
        "FREIA's day",
        "SATURN day",
      ],
      answer: 1,
    },
    {
      question: "Is dog food yummy?",
      answers: [
        "NO!",
        "no.",
        "yes.",
        "YES!",
      ],
      answer: 4,
    },
    {
      question: "How long is Ben?",
      answers: [
        "'",
        "'",
        "'",
        "'",
      ],
      answer: 1,
    },
    {
      question: "What is my favorite word?",
      answers: [
        "Bean",
        "Cracker",
        "Charity",
        "GikChonilz",
      ],
      answer: 3,
    },
    {
      question: "How money I???",
      answers: [
        "OOF!!!!!!!!!!!!!!",
        "Bikes!!!!!!!!!!!!",
        "Zeal Dih!!!!!!!!!",
        "Makicellotamalte!",
      ],
      answer: 2,
    },
    {
      question: "Boney Choney rip my face!",
      answers: [
        "Correct!",
        "Incorrect!",
        "True",
        "False",
      ],
      answer: 3,
    },
    {
      question: "Uh... well, it's time to eat now.",
      answers: [
        "Clip your clip",
        "Da poetat da",
        "No it snot!",
        "Rub my face!",
      ],
      answer: 4,
    },
    {
      question: "Bobby went under a desk. She sat down. Then, she died.",
      answers: [
        "The beginning.",
        "The end.",
        "Theginning",
        "Thend",
      ],
      answer: 3,
    },
    {
      question: "Bean bean pork bean bean pork bean",
      answers: [
        "MOTHER",
        "MOTHER",
        "MOTHER",
        "MOTHER",
      ],
      answer: 3,
    },
    {
      question: "Cine",
      answers: [
        "Mark",
        "Cess",
        "Ocoo",
        "Lol!",
      ],
      answer: 1,
    },
    {
      question: "Mate (OwO)b",
      answers: [
        "Beefalba",
        "Tame a \"Got Chi\" ",
        "Because '\"'\"'\"'\"!",
        "Patin",
      ],
      answer: 2,
    },
    {
      question: "Hit Ler! (Ler is my name.)",
      answers: [
        "Iron Woman",
        "Blacksmith",
        "Superwomen",
        "I ate some",
      ],
      answer: 4,
    },
    {
      question: "Haha lol you are really far in!",
      answers: [
        "Eeny!",
        "Musoo!",
        "Stick.",
        "Aota Lightbulb",
      ],
      answer: 2,
    },
    {
      question: "Selemun",
      answers: [
        "Musoo",
        "Trash",
        "This",
        "CMAS Test",
        "Eeny my life.",
      ],
      answer: 3,
    },
    {
      question: "This is a small quiz.",
      answers: [
        "True",
        "False",
        "Maybe",
        "So",
      ],
      answer: 1,
    },
    {
      question: "Bisicle",
      answers: [
        "#2",
        "Game",
        "Small",
        "Everybody",
      ],
      answer: 2,
    },
    {
      question: "How old are you?",
      answers: [
        "1",
        "2",
        "3",
        "100,000",
      ],
      answer: 4,
    },
    {
      question: "I can't help you right now.",
      answers: [
        "JH",
        "BH",
        "EH",
        "SH",
      ],
      answer: 1,
    },
    {
      question: "Ethan is cool!",
      answers: [
        "TRUE!",
        "True.",
        "False.",
        "FALSE!",
        "TRUE!!!⨯9999",
      ],
      answer: 5,
    },
    {
      question: "How much does my dead body cost?",
      answers: [
        "$50",
        "$0",
        "-$10,000",
        "$999,999",
      ],
      answer: 3,
    },
    {
      question: "Error processing request",
      answers: [
        "Bitwise operator cannot be converted to String.",
        "List metrics have not been defined.",
        "Your mom",
        "Press any key to quit program",
      ],
      answer: 3,
    },
    {
      question: "This is the 80th question.",
      answers: [
        "+3",
        "-1",
        "+2",
        "Yes",
      ],
      answer: 4,
    },
    {
      question: "Is Kirby worthy?",
      answers: [
        "No",
        "Neh",
        "Nope",
        "Nyet",
        "BeamNG.drive",
        "AOTA Lightbulb",
      ],
      answer: 6,
    },
    {
      question: "Guess",
      answers: [
        " ",
        " ",
      ],
      answer: 2,
    },
    {
      question: "tsus",
      answers: [
        "You sussy baka",
        "bifnut",
        "Among Us 2: The Impostor",
        "Echo chamber",
      ],
      answer: 2,
    },
    {
      question: "when you got soft diamonds:",
      answers: [
        "the diamonds are soft",
        "Murdjsownxjei Laskfhwvakrnsuren",
        "*dies*",
        "You sus",
      ],
      answer: 2,
    },
    {
      question: "Hardness of the rocks:",
      answers: [
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
        "9",
        "10",
      ],
      answer: 10,
    },
    {
      question: "The bunker bunker",
      answers: [
        "Innocent",
        "Not anymore ;)",
        "Nashed potatoes",
        "Isus",
      ],
      answer: 2,
    },
    {
      question: "It'll be engrained in you're brained",
      answers: [
        "*your",
        "*brain",
        "*It will",
        "*.",
      ],
      answer: 3,
    },
    {
      question: "This is the answer.",
      answers: [
        "Okay!",
      ],
      answer: 1,
    },
    {
      question: "are you a bef nugy?",
      answer: "yes",
    },
    {
      question: "Are you in da nile?",
      answers: [
        "Egypt",
        "The Nile",
        "Canada",
        "Breakfast",
      ],
      answer: 3,
    },
    {
      question: "Yo monus",
      answers: [
        "amonos?",
        "the monos?",
        "amogus?",
        "the ronos?",
      ],
      answer: 4,
    },
    {
      question: "Roses are red,",
      answers: [
        "Your mother.",
        "true",
        "facts",
        "no cap",
      ],
      answer: 4,
    },
    {
      question: "Bruno looks like water",
      answers: [
        ";)",
        "sussy~",
        "Apple bottom water",
        "Your mother.",
      ],
      answer: 2,
    },
    {
      question: "Wrong answers only!",
      answers: [
        "Right",
        "Wrong",
        "Wrong",
        "Wrong",
      ],
      answer: 2,
    },
    {
      question: "Wrong answers only!",
      answers: [
        "Wrong",
        "Wrong",
        "Wrong",
        "Right",
      ],
      answer: 3,
    },
    {
      question: "Do you have marbles?",
      answers: [
        "Feb balls?",
        "Mar balls?",
        "Jan balls?",
        "Sus balls?",
      ],
      answer: 2,
    },
    {
      question: "On a scale of 1...10, how bad is ice cream?",
      answers: [
        "0",
        "7",
        "11",
        "12",
      ],
      answer: 1,
    },
    {
      question: "Soda soda soda soda soda soad soda soda!",
      answers: [
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
      ],
      answer: 6,
    },
    {
      question: "POV: you start crying",
      answers: [
        "sussyyyyyyyyyy",
        "hehehehehehe",
        "pov: you turn into joe biden",
        "blue",
      ],
      answer: 3,
    },
    {
      question: "is that a wof reference??!?!??!!!",
      answers: [
        "yes",
      ],
      answer: 1,
    },
    {
      question: "That sounded a little sussy and you're making me uncomfortable and",
      answers: [
        "You finally woke up!",
        "Me estas poniendo nervioso",
        "I'm Navi the fairy!",
        "The Great Deku Tree asked me to be your partner from now on! Nice to meet you!",
        "The Great Deku Tree has summoned you. Let's get going right now",
        "Yahoo! Hi, Deez Nuts!",
      ],
      answer: 3,
    },
    {
      question: "Does bacon die?",
      answers: [
        "It may",
        "It may not",
        "You are bacon",
        "Don't die!",
      ],
      answer: 3,
    },
    {
      question: "BaconMomentTM",
      answers: [
        "Bakatotus",
        "Apotussy",
        "BakaMoment",
        "MeowMoment",
      ],
      answer: 4,
    },
    {
      question: "what?",
      answers: [
        "americongus",
        "I looooove mushrooms",
        "GikChonilz!?!?",
        "I have returned",
      ],
      answer: 1,
    },
    {
      question: "I chew ass",
      answers: [
        "sleep tracking app",
        "SMASH LIKE SMASH SUBSCRIBE DONT FORGET TO HIT THE BELL TO GET FUTURE NOTIFICATIONS AND I'LL SEE YOU GUYS IN THE NEXT VIDEO BYEEEEEEEEEEE",
        "taco bell",
        "wait actually how did you get to this question?",
      ],
      answer: 3,
    },
    {
      question: " ",
      answers: [
        ";)",
        " ",
        " ",
        " ",
      ],
      answer: 1,
    },
  ];
}